# Generated by Django 4.1.6 on 2023-02-04 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("ethnicity", models.CharField(max_length=100)),
                (
                    "height",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
            ],
        ),
    ]
